export interface ScriptLine {
  id: number;
  speaker?: string;
  text: string;
  scene: string;
  type?: 'dialogue' | 'action' | 'music';
}

export const scriptData: ScriptLine[] = [
  { id: 1, type: 'action', text: "Família hebreia conversando em volta da mesa. (mãe, filha, tia, pai)", scene: "Cena 1" },
  { id: 2, speaker: "Mãe", text: "Vamos filha! Não temos tempo a perder.", scene: "Cena 1" },
  { id: 3, speaker: "Filha", text: "Porque estamos apressados?", scene: "Cena 1" },
  { id: 4, speaker: "Mãe", text: "Porque Deus está trazendo julgamento sobre os deuses do Egito.", scene: "Cena 1" },
  { id: 5, speaker: "Filha", text: "Como assim?", scene: "Cena 1" },
  { id: 6, speaker: "Mãe", text: "ahhh...a meia noite uma praga vai alcançar todas as casas que não estiverem protegidas. A morte vai alcançar toda a Terra.", scene: "Cena 1" },
  { id: 7, speaker: "Filha", text: "Mamãe eu não quero morrer", scene: "Cena 1" },
  { id: 8, type: 'action', text: "(elas se abraçam)", scene: "Cena 1" },
  { id: 9, speaker: "Mãe", text: "Calma filha. Deus de Abraão Isaque e Jacó está conosco, a morte não vai nos alcançar. Agora vamos terminar de arrumar essa mesa, tem muita coisa para fazer aqui ainda.", scene: "Cena 1" },
  { id: 10, type: 'action', text: "Filha come uma folha", scene: "Cena 1" },
  { id: 11, speaker: "Filha", text: "Que erva amarga!", scene: "Cena 1" },
  { id: 12, speaker: "Mãe", text: "Filha! Não é para comer agora, precisa esperar colocar tudo na mesa!", scene: "Cena 1" },
  { id: 13, type: 'action', text: "Chega a irmã", scene: "Cena 1" },
  { id: 14, speaker: "Irmã", text: "Aqui está o cordeiro que falta.", scene: "Cena 1" },
  { id: 15, speaker: "Mãe", text: "A que bom", scene: "Cena 1" },
  { id: 16, speaker: "Pai", text: "O que eu imaginava, tive que dividir com todos os vizinhos.", scene: "Cena 1" },
  { id: 17, speaker: "Mãe", text: "A que ótimo, os pães sem fermentos estão cortados.", scene: "Cena 1" },
  { id: 18, speaker: "Irmã", text: "Eu demorei um pouco para trazer porque estava ventando muito lá fora. O fogo quase se apagou.", scene: "Cena 1" },
  { id: 19, speaker: "Mãe", text: "Não cozinhou em água fervente não é?", scene: "Cena 1" },
  { id: 20, speaker: "Irmã", text: "Não. Assado no forno como o Senhor nos ordenou.", scene: "Cena 1" },
  { id: 21, speaker: "Pai", text: "Já aspergi o sangue dele nas vigas superiores e nas laterais das portas. Oh céus, livre nossas casas das asas do anjo da morte.", scene: "Cena 1" },
  { id: 22, speaker: "Filha", text: "Não se preocupe papai, Deus está conosco.", scene: "Cena 1" },
  { id: 23, speaker: "Todos", text: "Amém!", scene: "Cena 1" },
  { id: 24, speaker: "Pai", text: "Vamos comer. Oremos: _Baruch atah Adonai, Eloheinu, melech haolam, hamotzi lechem min haaretz. Amém", scene: "Cena 1" },
  { id: 25, speaker: "Irmã", text: "Bom eu quero um pedacinho desse pão porque eu sei que você passou o dia inteiro fazendo.", scene: "Cena 1" },
  { id: 26, speaker: "Mãe", text: "Tá minha irmã", scene: "Cena 1" },
  { id: 27, speaker: "Irmã", text: "Deve estar uma delícia.", scene: "Cena 1" },
  { id: 28, speaker: "Mãe", text: "Eu também quero provar esse cordeiro, parece estar ótimo.", scene: "Cena 1" },
  { id: 29, speaker: "Filha", text: "Huuummmm...está uma delícia.", scene: "Cena 1" },
  { id: 30, speaker: "Pai", text: "Ah essas crianças, parecem que não tem com o que se preocupar.", scene: "Cena 1" },
  { id: 31, speaker: "Mãe", text: "Pois devia ser como uma e confiar que existe alguém que nos guarda.", scene: "Cena 1" },
  { id: 32, speaker: "Irmã", text: "Devia ter feito um suco de uva pra tomarmos. Já sei, eu vou até o poço para buscar a água.", scene: "Cena 1" },
  { id: 33, speaker: "Todos", text: "Não, não.", scene: "Cena 1" },
  { id: 34, speaker: "Pai", text: "Não podemos sair até que amanheça", scene: "Cena 1" },
  { id: 35, speaker: "Irmã", text: "Verdade, melhor obedecer.", scene: "Cena 1" },
  { id: 36, speaker: "Filha", text: "Hummm até essa erva amarga agora parece estar gostosa! Tia a senhora cozinha muito bem.", scene: "Cena 1" },
  { id: 37, speaker: "Irmã", text: "Obrigada meu amor.", scene: "Cena 1" },
  { id: 38, speaker: "Mãe", text: "Enquanto todos comemos aqui dentro, lá fora o medo e o pranto se preparam para assombrar os corações dos egípcios. O senhor ordenou e nós obedecemos. O sangue do Cordeiro está guardando a nossa casa. Essa é a nossa Páscoa! E o anjo da morte vai ter que passar por cima, porque confiamos que o Deus de Israel está guardando a nossa família. Mesmo que o caos se instale lá fora, nós podemos deitar e dormir o sono dos justos, porque nós confiamos que o senhor está guardando a nossa família. Que essa mesma paz invada sua casa invada sua família o sangue do Cordeiro está cobrindo a sua vida e o anjo da morte vai ter que passar por cima. Amém!!!", scene: "Cena 1" },
  
  { id: 39, type: 'music', speaker: "Música 1", text: "É páscoa – Puro Louvor", scene: "Cena 1" },

  { id: 40, speaker: "Mulher", text: "Mais um dia sem encontrar Esperança, minhas forças se perdem. Há doze anos as primeiras gotas de sangue vieram, achei que fosse algo normal, mas então elas continuaram crescendo, até que se tornaram um oceano de fracasso dentro de mim (gemido de dor). Alguns dizem ser maldição, ou ficar alguma hemorragia que logo vai passar, o cheiro que ficou em minha casa, e as vergonhas expostas pelos estrangeiros que passavam pela minha aldeia, não estão escritas nas páginas da Bíblia (gemido longo de dor). As lágrimas decidiram dançar sobre meu rosto. Saúde se despediu do meu sangue e parece que nunca mais vai voltar a morar dentro de mim. Que mal eu fiz pra merecer tamanho castigo? (Choro) ninguém pode imaginar o que eu passei, mas isso logo vai passar, eu vou encontrar um feiticeiro ou um Boticário que possa me ajudar! Vai passar!", scene: "Cena 2" },
  { id: 41, type: 'action', text: "Dois homens entram conversando.", scene: "Cena 2" },
  { id: 42, speaker: "Homem", text: "O que essa mulher imunda está fazendo aqui? Segundo a lei de Moisés, tudo o que ela tocar se tornará imundo por aqui. A cama que ela dorme e até mesmo a cadeira que ela senta, a roupa que ela veste, nós não podemos permitir que Cafarnaum seja infectada com essa maldição que acompanha essa mulher.", scene: "Cena 2" },
  { id: 43, type: 'action', text: "Jesus entra com uma multidão, todos falando ao mesmo tempo.", scene: "Cena 2" },
  { id: 44, speaker: "Mulher", text: "Então esse é YESHUA? (Risos) Jesus, o homem que cura? Sim, há uma força diferente em seu olhar, eu posso ver! Basta tocá-lo e eu vou ser curada! Não, eu não posso mais acreditar nessas mentiras, não deu certo antes porque daria certo agora? Mas eu posso pelo menos tentar, sim basta tocá-lo e eu vou ser curada, eu preciso acreditar, eu preciso acreditar! (Gemidos)", scene: "Cena 2" },
  { id: 45, type: 'action', text: "A mulher se esforça para se aproximar de Jesus, finalmente ela consegue tocar um uma parte de suas vestes e então Jesus para, a multidão para também.", scene: "Cena 2" },
  { id: 46, type: 'action', text: "- Pausa", scene: "Cena 2" },
  { id: 47, speaker: "Jesus", text: "Quem me tocou?", scene: "Cena 2" },
  { id: 48, speaker: "Discípulo", text: "Mestre, a multidão te aperta e te oprime e o Senhor pergunta quem te tocou?", scene: "Cena 2" },
  { id: 49, speaker: "Jesus", text: "Alguém me tocou eu senti, de mim saiu poder. Quem me tocou?", scene: "Cena 2" },
  { id: 50, speaker: "Mulher", text: "Fui eu mestre, me perdoe, mas há 12 anos eu sofro desse mal, já não sou mais conhecida pelo meu nome, mas somente por impura.", scene: "Cena 2" },
  { id: 51, speaker: "Jesus", text: "Filha, a tua fé te curou.", scene: "Cena 2" },
  { id: 52, speaker: "Mulher", text: "EU FUI CURADA (risos) EU FUI CURADA!", scene: "Cena 2" },
  { id: 53, type: 'action', text: "(sai da cena)", scene: "Cena 2" },

  { id: 54, type: 'music', speaker: "Música 2", text: "Galileu – Tatiana Costa (Débora)", scene: "Cena 2" },

  { id: 55, type: 'action', text: "Discípulos e Jesus a mesa estão todos na casa de Simão, conversas, risos. Alguns discípulos contam de alguns milagres que aconteceram:", scene: "Cena 3" },
  { id: 56, speaker: "Pedro", text: "A meus amigos, aquela noite foi indescritível para mim, um misto de medo, fé e coragem. Nunca poderia imaginar que um ser humano andaria sobre as águas.", scene: "Cena 3" },
  { id: 57, speaker: "André", text: "É nós vimos o seu medo mesmo quando começou a afundar... (todos começam a rir)", scene: "Cena 3" },
  { id: 58, speaker: "Pedro", text: "Pelo menos eu tentei e você? Vocês riem agora, mas quem foi o corajoso ein? Quem foi?", scene: "Cena 3" },
  { id: 59, type: 'action', text: "Neste momento entra Maria de maneira bem discreta, se aproxima de Jesus e começa a ungir os seus pés (espirrar perfume em várias partes da igreja). De repente a conversa cessa e começam um burburinho...", scene: "Cena 3" },
  { id: 60, speaker: "Pedro", text: "Que cheiro é esse?", scene: "Cena 3" },
  { id: 61, speaker: "Mateus", text: "Deve ser do pão assando...", scene: "Cena 3" },
  { id: 62, speaker: "Pedro", text: "Pão? Está delirando de fome Mateus? Sinta o cheiro desse perfume... Isso é...", scene: "Cena 3" },
  { id: 63, speaker: "Judas", text: "Nardo! Nardo puro, perfume caríssimo, por que tanto desperdício? Poderia ter vendido e dado o dinheiro aos pobres...", scene: "Cena 3" },
  { id: 64, speaker: "Jesus", text: "Não incomode a mulher, poque os pobres sempre terei convosco, mas a Mim, me ungi como para o meu sepultamento... Essa mulher recebeu de Mim o amor incondicional e entendo isso não mediu esforços para me adorar! Muito receberam cura, perdão, amor e salvação o que fazem com tal benção?", scene: "Cena 3" },

  { id: 65, type: 'music', speaker: "Música 3", text: "Perfume – Suzana", scene: "Cena 3" },

  { id: 66, type: 'action', text: "Luz baixa, algumas velas acesas", scene: "Cena 4" },
  { id: 67, type: 'action', text: "Mesa com os 12 discípulos e Jesus lavando os pés um por um.", scene: "Cena 4" },
  { id: 68, type: 'action', text: "Todos em silêncio, parecem não entender o que está acontecendo, até que Jesus começa a lavar os pés de Pedro.", scene: "Cena 4" },
  { id: 69, speaker: "Pedro", text: "Senhor, vais lavar os meus pés?", scene: "Cena 4" },
  { id: 70, speaker: "Jesus", text: "Você não compreende agora o que estou lhe fazendo; mais tarde, porém, entenderá", scene: "Cena 4" },
  { id: 71, speaker: "Pedro", text: "Não; nunca lavarás os meus pés", scene: "Cena 4" },
  { id: 72, speaker: "Jesus", text: "Se eu não os lavar, você não terá parte comigo", scene: "Cena 4" },
  { id: 73, speaker: "Pedro", text: "Então, Senhor, não apenas os meus pés, mas também as minhas mãos e a minha cabeça!", scene: "Cena 4" },
  { id: 74, speaker: "Jesus", text: "Quem já se banhou precisa apenas lavar os pés; todo o seu corpo está limpo. Vocês estão limpos, mas nem todos.", scene: "Cena 4" },
  { id: 75, type: 'action', text: "Jesus tornou a vestir sua capa e voltou ao seu lugar.", scene: "Cena 4" },
  { id: 76, speaker: "Jesus", text: "Tomai e reparti-o entre vós pois vos digo que não beberei do fruto da vide até que venha o reino de Deus.", scene: "Cena 4" },
  { id: 77, type: 'action', text: "Inicia a música enquanto Jesus e os discípulos continuam bebendo, repartisse o pão e eles saem de cena antes ao final da primeira estrofe.", scene: "Cena 4" },

  { id: 78, type: 'music', speaker: "Música 4", text: "Tereis lugar – Robson Fonseca (Bruno)", scene: "Cena 4" },
  { id: 79, type: 'action', text: "Durante a música Jesus e os discípulos encenam como se estivessem no Getsêmani, Jesus contando para eles o que aconteceria.", scene: "Cena 4" },
  { id: 80, type: 'action', text: "Na última estrofe entram os soldados levam Jesus e os discípulos ficam ali como que perdidos em desespero.", scene: "Cena 4" },
  { id: 81, type: 'action', text: "Antes da música acabar todos saem. Para voltar na próxima cena com a música.", scene: "Cena 4" },

  { id: 82, type: 'action', text: "Antes do início da música a multidão entra com Jesus carregando a cruz. Quando iniciar martelar as mãos de Jesus começa a música", scene: "Cena 5" },
  { id: 83, type: 'music', speaker: "Música 5", text: "Ouço o som – Laura Morena (Cássia e Jéssika)", scene: "Cena 5" },
  { id: 84, type: 'action', text: "Encenar toda a música.", scene: "Cena 5" },
  { id: 85, speaker: "Narrador", text: "Muitas vezes ignorei tudo isso e não parei para pensar que todo amor e sacrifício vai além da cruz! Que cena! Quanta dor! Ao contemplar tamanho sacrifício quantas vezes me perguntei se realmente eu merecia... Um amor capaz se se entregar sem nenhuma recompensa, sem nenhuma vantagem, apenas por amor...é surreal!", scene: "Cena 5" },

  { id: 86, type: 'music', speaker: "Música 6", text: "Não tente Entender – Renata, Fernanda e Luiz", scene: "Cena 5" },
  { id: 87, speaker: "Narrador", text: "Após a morte de Jesus, seus discípulos e seguidores ficaram atônitos, como se não soubessem para onde ir ou como recomeçar a vida sem o direcionamento do Mestre. Até parecia que eles se esqueceram de Suas palavras... Ele disse que seria entregue e que morreria, mas que ressuscitaria e os encontraria na Galileia.", scene: "Cena 5" },
  { id: 88, type: 'action', text: "Ao se reunirem à mesa eles tentam se consolar.", scene: "Cena 5" },

  { id: 89, type: 'action', text: "Os discípulos em volta da mesa, conversando sobre os últimos acontecimentos.", scene: "Cena 6" },
  { id: 90, speaker: "André", text: "O que faremos agora? Voltaremos para a pescaria?", scene: "Cena 6" },
  { id: 91, speaker: "João", text: "Como podes já pensar essas coisas André? Eu ainda estou sem acreditar em tudo que enfrentamos nesses últimos dias, parece um pesadelo!", scene: "Cena 6" },
  { id: 92, speaker: "Tiago", text: "O que será de nós agora? Nossa vida foi transformada nesses últimos anos, como viveremos daqui pra frente?", scene: "Cena 6" },
  { id: 93, type: 'action', text: "Nesse momento Jesus aparece no meio deles.", scene: "Cena 6" },
  { id: 94, speaker: "Jesus", text: "Paz Seja convosco! Por que estão perturbados e por que surgem dúvidas no coração de vocês? Vejam as minhas mãos e os meus pés. Sou eu mesmo! Toquem-me e vejam; um espírito não tem carne nem ossos, como estão vendo que eu tenho.", scene: "Cena 6" },
  { id: 95, speaker: "Narrador", text: "Tendo dito isso, mostrou-lhes as mãos e os pés. Por não crerem ainda, tão cheios de alegria e de espanto, ele lhes perguntou: — Vocês têm aqui algo para comer?", scene: "Cena 6" },
  { id: 96, type: 'action', text: "Deram-lhe um pedaço de peixe assado, e ele o comeu na presença deles.", scene: "Cena 6" },
  { id: 97, speaker: "João", text: "Eu sabia! Bem no fundo eu sabia! Eu sempre soube que não seria em vão! O Senhor prometeu e não falhou, foi por amor! O Senhor me ama e por isso eu te louvo ó Mestre poque se entregaste por mim!", scene: "Cena 6" },

  { id: 98, type: 'music', speaker: "Música 7", text: "Ao pé da Cruz – Coral Puro Louvor", scene: "Cena 6" },

  { id: 99, speaker: "Mãe", text: "Venham todos! O almoço já está pronto!", scene: "Cena 7" },
  { id: 100, speaker: "Filha", text: "O cheiro está ótimo mamãe! Já estou com fome!", scene: "Cena 7" },
  { id: 101, speaker: "Mãe", text: "Marido, por favor sem celular à mesa. Hoje é um dia especial.", scene: "Cena 7" },
  { id: 102, type: 'action', text: "Tia entra com suco de uva", scene: "Cena 7" },
  { id: 103, speaker: "Tia", text: "pronto agora podemos.", scene: "Cena 7" },
  { id: 104, speaker: "Papai", text: "Vamos orar?", scene: "Cena 7" },
  { id: 105, speaker: "Mãe", text: "Vamos fazer diferente? Antes de orarmos, que tal agradecermos ao Senhor por algumas bençãos que ele nos tem concedido?", scene: "Cena 7" },
  { id: 106, speaker: "Tia", text: "Ótima ideia! Eu agradeço pela saúde, são tantas doenças, tantos males tem atingido o povo de Deus e eu agradeço por ter saúde!", scene: "Cena 7" },
  { id: 107, speaker: "Papai", text: "E vocês tem algo especial que gostariam de agradecer?", scene: "Cena 7" },
  { id: 108, type: 'action', text: "Dar oportunidade de a igreja agradecer.", scene: "Cena 7" },
  { id: 109, speaker: "Mãe", text: "Eu agradeço pela salvação em Jesus! Em 2026 poder celebrar a Páscoa e ter a certeza de que tudo o que Jesus passou foi por amor incondicional, isso traz uma gratidão, mas também traz o desejo de se render aos pés desse Deus de tanto amor e compaixão! Em diversos momentos nos sentimos sós, que os problemas e os fardos desta vida estão tão pesados que parece que não vamos suportar! Mas saiba que toda dor, sacrifício, renúncia, tudo o Cristo suportou foi por você! Então, lembre-se você não está só, um amor imenso e sem medida foi derramado na cruz por você!", scene: "Cena 7" },

  { id: 110, type: 'music', speaker: "Música 8", text: "Por você – Coral Iasp (grande coro)", scene: "Cena 7" },
  { id: 111, type: 'action', text: "Oração:", scene: "Cena 7" }
];
